#!/usr/bin/env python3
#
#  gen_glyphs.py
#  asciiplay
#
#  Created by Piotr Panasewicz on 10/08/2026.
#  Copyright © 2026 Codice. All rights reserved.
#
#  Licensed under the MIT licence. See LICENSE in the project root
#  for the full text.
#
"""Rasterise a monospace font into a coverage table for asciiplay.

Emits glyph_table.h: for every printable ASCII character, an 8x16 array of
ink-coverage bytes (0..255).  Re-run against a different font if your terminal
uses one, and the shape matching will follow it.

  python3 gen_glyphs.py [font.ttf] > glyph_table.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else \
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
CW, CH, SS = 8, 16, 64          # cell width, cell height, rasterisation size

f = ImageFont.truetype(FONT, SS)
asc, desc = f.getmetrics()
bw, bh = int(round(f.getlength("M"))), asc + desc

rows = []
for c in range(32, 127):
    im = Image.new("L", (bw, bh), 0)
    ImageDraw.Draw(im).text((0, 0), chr(c), font=f, fill=255)
    px = im.resize((CW, CH), Image.LANCZOS).tobytes()
    rows.append((c, px))

# the same file header the checked-in sources carry, so regenerating the table
# does not quietly drop it
print("//")
print("//  glyph_table.h")
print("//  asciiplay")
print("//")
print("//  Created by Piotr Panasewicz on 10/08/2026.")
print("//  Copyright © 2026 Codice. All rights reserved.")
print("//")
print("//  Licensed under the MIT licence. See LICENSE in the project root")
print("//  for the full text.")
print("//")
print("// Generated by gen_glyphs.py -- do not edit.")
print(f"// font: {FONT}")
print("#pragma once")
print("#include <cstdint>")
print(f"constexpr int GLYPH_W = {CW};")
print(f"constexpr int GLYPH_H = {CH};")
print(f"constexpr int GLYPH_N = {len(rows)};")
print("constexpr char GLYPH_FIRST = 32;")
print("constexpr uint8_t GLYPH_COVERAGE[GLYPH_N][GLYPH_W * GLYPH_H] = {")
for c, px in rows:
    disp = chr(c) if c != 92 else "\\\\"
    body = ",".join(str(b) for b in px)
    print(f"  {{{body}}}, // '{disp}'")
print("};")
